// flow-typed signature: e171a0f4adb2522742a573944bc20784
// flow-typed version: <<STUB>>/@types/classnames_v^2.2.9/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
