// flow-typed signature: 50685e81ff0e9667915949a58a25c94b
// flow-typed version: <<STUB>>/@types/prop-types_v^15.7.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/prop-types' {
  declare module.exports: any;
}
