// flow-typed signature: 6b3e411701babc2e6f6520580da2616a
// flow-typed version: <<STUB>>/@commitlint/cli_v^5.2.5/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/cli/fixtures/empty/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/extends-root/extended' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/inner-scope/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/inner-scope/inner-scope/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/outer-scope/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/parser-preset/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/parser-preset/parser-preset' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/signoff/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/fixtures/simple/commitlint.config' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/cli' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/cli.test' {
  declare module.exports: any;
}

declare module '@commitlint/cli/lib/help' {
  declare module.exports: any;
}

declare module '@commitlint/cli/src/cli' {
  declare module.exports: any;
}

declare module '@commitlint/cli/src/cli.test' {
  declare module.exports: any;
}

declare module '@commitlint/cli/src/help' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/cli/fixtures/empty/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/empty/commitlint.config'>;
}
declare module '@commitlint/cli/fixtures/extends-root/extended.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/extends-root/extended'>;
}
declare module '@commitlint/cli/fixtures/inner-scope/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/inner-scope/commitlint.config'>;
}
declare module '@commitlint/cli/fixtures/inner-scope/inner-scope/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/inner-scope/inner-scope/commitlint.config'>;
}
declare module '@commitlint/cli/fixtures/outer-scope/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/outer-scope/commitlint.config'>;
}
declare module '@commitlint/cli/fixtures/parser-preset/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/parser-preset/commitlint.config'>;
}
declare module '@commitlint/cli/fixtures/parser-preset/parser-preset.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/parser-preset/parser-preset'>;
}
declare module '@commitlint/cli/fixtures/signoff/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/signoff/commitlint.config'>;
}
declare module '@commitlint/cli/fixtures/simple/commitlint.config.js' {
  declare module.exports: $Exports<'@commitlint/cli/fixtures/simple/commitlint.config'>;
}
declare module '@commitlint/cli/index' {
  declare module.exports: $Exports<'@commitlint/cli'>;
}
declare module '@commitlint/cli/index.js' {
  declare module.exports: $Exports<'@commitlint/cli'>;
}
declare module '@commitlint/cli/lib/cli.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/cli'>;
}
declare module '@commitlint/cli/lib/cli.test.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/cli.test'>;
}
declare module '@commitlint/cli/lib/help.js' {
  declare module.exports: $Exports<'@commitlint/cli/lib/help'>;
}
declare module '@commitlint/cli/src/cli.js' {
  declare module.exports: $Exports<'@commitlint/cli/src/cli'>;
}
declare module '@commitlint/cli/src/cli.test.js' {
  declare module.exports: $Exports<'@commitlint/cli/src/cli.test'>;
}
declare module '@commitlint/cli/src/help.js' {
  declare module.exports: $Exports<'@commitlint/cli/src/help'>;
}
