// flow-typed signature: a487dd1c662bbd6d29b8aae9762ee8b0
// flow-typed version: <<STUB>>/babel-plugin-istanbul_v^6.0.0/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-istanbul' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-istanbul/lib' {
  declare module.exports: any
}

declare module 'babel-plugin-istanbul/lib/load-nyc-config-sync' {
  declare module.exports: any
}

// Filename aliases
declare module 'babel-plugin-istanbul/lib/index' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib'>
}
declare module 'babel-plugin-istanbul/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib'>
}
declare module 'babel-plugin-istanbul/lib/load-nyc-config-sync.js' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib/load-nyc-config-sync'>
}
