// flow-typed signature: 7c572c7e83342c90888230a4980a0384
// flow-typed version: <<STUB>>/copy_v^0.3.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy/bin/cli' {
  declare module.exports: any;
}

declare module 'copy/lib/base' {
  declare module.exports: any;
}

declare module 'copy/lib/dest' {
  declare module.exports: any;
}

declare module 'copy/lib/invalid' {
  declare module.exports: any;
}

declare module 'copy/lib/once' {
  declare module.exports: any;
}

declare module 'copy/lib/recurse' {
  declare module.exports: any;
}

declare module 'copy/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy/bin/cli.js' {
  declare module.exports: $Exports<'copy/bin/cli'>;
}
declare module 'copy/index' {
  declare module.exports: $Exports<'copy'>;
}
declare module 'copy/index.js' {
  declare module.exports: $Exports<'copy'>;
}
declare module 'copy/lib/base.js' {
  declare module.exports: $Exports<'copy/lib/base'>;
}
declare module 'copy/lib/dest.js' {
  declare module.exports: $Exports<'copy/lib/dest'>;
}
declare module 'copy/lib/invalid.js' {
  declare module.exports: $Exports<'copy/lib/invalid'>;
}
declare module 'copy/lib/once.js' {
  declare module.exports: $Exports<'copy/lib/once'>;
}
declare module 'copy/lib/recurse.js' {
  declare module.exports: $Exports<'copy/lib/recurse'>;
}
declare module 'copy/lib/utils.js' {
  declare module.exports: $Exports<'copy/lib/utils'>;
}
