// flow-typed signature: f7c83d7748eb79b9a18976965434f5ed
// flow-typed version: <<STUB>>/eslint-watch_v^3.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-watch/build/arg-parser' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/eslint/cli' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/eslint/help' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/executor' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/formatters/helpers/characters' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/formatters/helpers/error-warning' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/formatters/helpers/success' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/formatters/simple-detail' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/formatters/simple-success' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/formatters/simple' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/index' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/logger' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/options' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/settings' {
  declare module.exports: any;
}

declare module 'eslint-watch/build/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-watch/build/arg-parser.js' {
  declare module.exports: $Exports<'eslint-watch/build/arg-parser'>;
}
declare module 'eslint-watch/build/eslint/cli.js' {
  declare module.exports: $Exports<'eslint-watch/build/eslint/cli'>;
}
declare module 'eslint-watch/build/eslint/help.js' {
  declare module.exports: $Exports<'eslint-watch/build/eslint/help'>;
}
declare module 'eslint-watch/build/executor.js' {
  declare module.exports: $Exports<'eslint-watch/build/executor'>;
}
declare module 'eslint-watch/build/formatters/helpers/characters.js' {
  declare module.exports: $Exports<'eslint-watch/build/formatters/helpers/characters'>;
}
declare module 'eslint-watch/build/formatters/helpers/error-warning.js' {
  declare module.exports: $Exports<'eslint-watch/build/formatters/helpers/error-warning'>;
}
declare module 'eslint-watch/build/formatters/helpers/success.js' {
  declare module.exports: $Exports<'eslint-watch/build/formatters/helpers/success'>;
}
declare module 'eslint-watch/build/formatters/simple-detail.js' {
  declare module.exports: $Exports<'eslint-watch/build/formatters/simple-detail'>;
}
declare module 'eslint-watch/build/formatters/simple-success.js' {
  declare module.exports: $Exports<'eslint-watch/build/formatters/simple-success'>;
}
declare module 'eslint-watch/build/formatters/simple.js' {
  declare module.exports: $Exports<'eslint-watch/build/formatters/simple'>;
}
declare module 'eslint-watch/build/index.js' {
  declare module.exports: $Exports<'eslint-watch/build/index'>;
}
declare module 'eslint-watch/build/logger.js' {
  declare module.exports: $Exports<'eslint-watch/build/logger'>;
}
declare module 'eslint-watch/build/options.js' {
  declare module.exports: $Exports<'eslint-watch/build/options'>;
}
declare module 'eslint-watch/build/settings.js' {
  declare module.exports: $Exports<'eslint-watch/build/settings'>;
}
declare module 'eslint-watch/build/watcher.js' {
  declare module.exports: $Exports<'eslint-watch/build/watcher'>;
}
