// flow-typed signature: 6b97c48fe0d70eb7fe54171522b22627
// flow-typed version: <<STUB>>/flow-copy-source_vhttps://github.com/jedwards1211/flow-copy-source#no-watch/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-copy-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-copy-source' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-copy-source/bin/flow-copy-source' {
  declare module.exports: any
}

declare module 'flow-copy-source/src' {
  declare module.exports: any
}

declare module 'flow-copy-source/src/index.test' {
  declare module.exports: any
}

declare module 'flow-copy-source/src/kefir-copy-file' {
  declare module.exports: any
}

declare module 'flow-copy-source/src/kefir-glob' {
  declare module.exports: any
}

// Filename aliases
declare module 'flow-copy-source/bin/flow-copy-source.js' {
  declare module.exports: $Exports<'flow-copy-source/bin/flow-copy-source'>
}
declare module 'flow-copy-source/src/index' {
  declare module.exports: $Exports<'flow-copy-source/src'>
}
declare module 'flow-copy-source/src/index.js' {
  declare module.exports: $Exports<'flow-copy-source/src'>
}
declare module 'flow-copy-source/src/index.test.js' {
  declare module.exports: $Exports<'flow-copy-source/src/index.test'>
}
declare module 'flow-copy-source/src/kefir-copy-file.js' {
  declare module.exports: $Exports<'flow-copy-source/src/kefir-copy-file'>
}
declare module 'flow-copy-source/src/kefir-glob.js' {
  declare module.exports: $Exports<'flow-copy-source/src/kefir-glob'>
}
