// flow-typed signature: 113e0d46b29531ba54c76e52e6d30bfb
// flow-typed version: <<STUB>>/nyc_v^15.1.0/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyc' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nyc/bin/nyc' {
  declare module.exports: any
}

declare module 'nyc/bin/wrap' {
  declare module.exports: any
}

declare module 'nyc/lib/commands/check-coverage' {
  declare module.exports: any
}

declare module 'nyc/lib/commands/helpers' {
  declare module.exports: any
}

declare module 'nyc/lib/commands/instrument' {
  declare module.exports: any
}

declare module 'nyc/lib/commands/merge' {
  declare module.exports: any
}

declare module 'nyc/lib/commands/report' {
  declare module.exports: any
}

declare module 'nyc/lib/config-util' {
  declare module.exports: any
}

declare module 'nyc/lib/fs-promises' {
  declare module.exports: any
}

declare module 'nyc/lib/hash' {
  declare module.exports: any
}

declare module 'nyc/lib/instrumenters/istanbul' {
  declare module.exports: any
}

declare module 'nyc/lib/instrumenters/noop' {
  declare module.exports: any
}

declare module 'nyc/lib/process-args' {
  declare module.exports: any
}

declare module 'nyc/lib/register-env' {
  declare module.exports: any
}

declare module 'nyc/lib/source-maps' {
  declare module.exports: any
}

declare module 'nyc/lib/wrap' {
  declare module.exports: any
}

// Filename aliases
declare module 'nyc/bin/nyc.js' {
  declare module.exports: $Exports<'nyc/bin/nyc'>
}
declare module 'nyc/bin/wrap.js' {
  declare module.exports: $Exports<'nyc/bin/wrap'>
}
declare module 'nyc/index' {
  declare module.exports: $Exports<'nyc'>
}
declare module 'nyc/index.js' {
  declare module.exports: $Exports<'nyc'>
}
declare module 'nyc/lib/commands/check-coverage.js' {
  declare module.exports: $Exports<'nyc/lib/commands/check-coverage'>
}
declare module 'nyc/lib/commands/helpers.js' {
  declare module.exports: $Exports<'nyc/lib/commands/helpers'>
}
declare module 'nyc/lib/commands/instrument.js' {
  declare module.exports: $Exports<'nyc/lib/commands/instrument'>
}
declare module 'nyc/lib/commands/merge.js' {
  declare module.exports: $Exports<'nyc/lib/commands/merge'>
}
declare module 'nyc/lib/commands/report.js' {
  declare module.exports: $Exports<'nyc/lib/commands/report'>
}
declare module 'nyc/lib/config-util.js' {
  declare module.exports: $Exports<'nyc/lib/config-util'>
}
declare module 'nyc/lib/fs-promises.js' {
  declare module.exports: $Exports<'nyc/lib/fs-promises'>
}
declare module 'nyc/lib/hash.js' {
  declare module.exports: $Exports<'nyc/lib/hash'>
}
declare module 'nyc/lib/instrumenters/istanbul.js' {
  declare module.exports: $Exports<'nyc/lib/instrumenters/istanbul'>
}
declare module 'nyc/lib/instrumenters/noop.js' {
  declare module.exports: $Exports<'nyc/lib/instrumenters/noop'>
}
declare module 'nyc/lib/process-args.js' {
  declare module.exports: $Exports<'nyc/lib/process-args'>
}
declare module 'nyc/lib/register-env.js' {
  declare module.exports: $Exports<'nyc/lib/register-env'>
}
declare module 'nyc/lib/source-maps.js' {
  declare module.exports: $Exports<'nyc/lib/source-maps'>
}
declare module 'nyc/lib/wrap.js' {
  declare module.exports: $Exports<'nyc/lib/wrap'>
}
