// flow-typed signature: a008e63f3a4842b0c8cb20462ae8750a
// flow-typed version: <<STUB>>/prettier-eslint_v^8.8.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-eslint/dist' {
  declare module.exports: any;
}

declare module 'prettier-eslint/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-eslint/dist/index' {
  declare module.exports: $Exports<'prettier-eslint/dist'>;
}
declare module 'prettier-eslint/dist/index.js' {
  declare module.exports: $Exports<'prettier-eslint/dist'>;
}
declare module 'prettier-eslint/dist/utils.js' {
  declare module.exports: $Exports<'prettier-eslint/dist/utils'>;
}
