// flow-typed signature: e5527cd8879805c3cc55c34ea6fa7bcb
// flow-typed version: <<STUB>>/travis-deploy-once_v^4.3.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-deploy-once'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-deploy-once' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'travis-deploy-once/bin/travis-deploy-once' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/cli' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/elect-build-leader' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/get-jobs' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/get-logger' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/get-token' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/get-travis-url' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/travis-deploy-once' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/validate' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/verify-jobs-state' {
  declare module.exports: any;
}

declare module 'travis-deploy-once/lib/wait-for-other-jobs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'travis-deploy-once/bin/travis-deploy-once.js' {
  declare module.exports: $Exports<'travis-deploy-once/bin/travis-deploy-once'>;
}
declare module 'travis-deploy-once/cli.js' {
  declare module.exports: $Exports<'travis-deploy-once/cli'>;
}
declare module 'travis-deploy-once/index' {
  declare module.exports: $Exports<'travis-deploy-once'>;
}
declare module 'travis-deploy-once/index.js' {
  declare module.exports: $Exports<'travis-deploy-once'>;
}
declare module 'travis-deploy-once/lib/elect-build-leader.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/elect-build-leader'>;
}
declare module 'travis-deploy-once/lib/get-jobs.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/get-jobs'>;
}
declare module 'travis-deploy-once/lib/get-logger.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/get-logger'>;
}
declare module 'travis-deploy-once/lib/get-token.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/get-token'>;
}
declare module 'travis-deploy-once/lib/get-travis-url.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/get-travis-url'>;
}
declare module 'travis-deploy-once/lib/travis-deploy-once.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/travis-deploy-once'>;
}
declare module 'travis-deploy-once/lib/validate.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/validate'>;
}
declare module 'travis-deploy-once/lib/verify-jobs-state.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/verify-jobs-state'>;
}
declare module 'travis-deploy-once/lib/wait-for-other-jobs.js' {
  declare module.exports: $Exports<'travis-deploy-once/lib/wait-for-other-jobs'>;
}
