// flow-typed signature: 27ff9fed269308ecdc5dde02eb8796a1
// flow-typed version: <<STUB>>/@material-ui/types_v^4.1.1/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/types' {
  declare module.exports: any
}
