// flow-typed signature: 2d4b55037aa06ec2c0f22c29ebd97ef3
// flow-typed version: <<STUB>>/@jedwards1211/commitlint-config_v^1.0.2/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/commitlint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/commitlint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jedwards1211/commitlint-config/commitlint.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jedwards1211/commitlint-config/commitlint.config.js' {
  declare module.exports: $Exports<'@jedwards1211/commitlint-config/commitlint.config'>;
}
