// flow-typed signature: 0aa06c4e27f7ffc928e3deeaeb373387
// flow-typed version: <<STUB>>/@jedwards1211/eslint-config_v^2.0.2/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/eslint-config' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@jedwards1211/eslint-config/index' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config'>
}
declare module '@jedwards1211/eslint-config/index.js' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config'>
}
